spring.application.name=user-service

# ===============================
# CONFIGURATION DU SERVEUR
# ===============================
server.port=8085

# ===============================
# CONFIGURATION H2 (Base isolée)
# ===============================
spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Activation Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ===============================
# JPA & SQL
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===============================
# SÉCURITÉ (JWT)
# ===============================
# Garde bien ces noms de variables car il les utilise sûrement dans son code Java
jwt.secret=EnerShareSuperSecretKeyPourProtegerLesMotsDePasseDesUtilisateurs123456789
jwt.expiration=3600000

# ===============================
# SWAGGER (Doc API)
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# JSON FORMAT
# ===============================
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC